# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190502_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
