# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
